language: node_js

node_js:
  - "10"

install:
  - npm install -g firebase-tools
  - yarn install

script:
  - echo "========== Build Start =========="
  - yarn run build

branches:
  only:
    - master

cache: yarn

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  project: $FIREBASE_PROJECT