version: 2
jobs:
  deploy_dev:
    docker:
      - image: circleci/node:10.17
    steps:
      - run:
        name: env
        command: |
          echo 'export $STAGE_REACT_APP_APIKEY' >> $REACT_APP_APIKEY
          echo 'export $STAGE_STAGE_REACT_APP_AUTH_DOMAIN' >> $REACT_APP_AUTH_DOMAIN
          echo 'export $STAGE_REACT_APP_DATABASE_URL' >> $REACT_APP_DATABASE_URL
          echo 'export $STAGE_REACT_APP_PROJECT_ID' >> $REACT_APP_PROJECT_ID
          echo 'export $STAGE_REACT_APP_STORAGE_BUCKET' >> $REACT_APP_STORAGE_BUCKET
          echo 'export $STAGE_REACT_APP_MESSAGING_SENDER_ID' >> $REACT_APP_MESSAGING_SENDER_ID
          echo 'export $STAGE_REACT_APP_DEMO_EVENTID' >> $REACT_APP_DEMO_EVENTID
      - checkout
      - run:
          name: Install Depencies
          command: yarn
      - run:
          name: build
          command: yarn build
      - run:
          name: select firebase project
          command: ./node_modules/.bin/firebase use put-your-hands-up-test
      - run:
          name: deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --only hosting

workflows:
  version: 2
  deploy_dev:
    jobs:
      - deploy_dev:
          filters:
            branches:
              only: develop
